# Generated by Django 5.1 on 2024-08-27 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('user', 'public_url')},
        ),
    ]
